name: Prepare repository
description: Prepare repository for further actions
inputs:
  NODE_AUTH_TOKEN:
    description: A Node auth token / GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up pnpm v9
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Set up Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        registry-url: https://npm.pkg.github.com/
        scope: '@radoslavirha'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}