name: Pull request

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-addon-changes:
    name: Check addon changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-addons-matrix.outputs.json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 📂 Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/paths-filter.yml
      - name: Compose array of changed addons
        id: addons
        if: ${{ steps.filter.outputs.changes != '[]' }}
        run: |
          addons=()
          for path in $(echo "${{ steps.filter.outputs.changes }}" | jq -r '.[]'); do
            if [ -f "addons/$path/package.json" ]; then
              name=$(jq -r '.name' "addons/$path/package.json")
              version=$(jq -r '.version' "addons/$path/package.json")
              addons+=("{\"name\":\"$name\",\"version\":\"$version\"}")
            fi
          done
          echo "addons=$(jq -c -n '$addons')" >> "$GITHUB_OUTPUT"
      - name: Set Addons matrix
        id: set-addons-matrix
        if: ${{ steps.addons.outcome == 'success' && steps.addons.outputs.addons != '[]' }}
        uses: nickofthyme/object-remap@v3
        with:
          include.*.name: ${{ toJSON(fromJSON(steps.addons.outputs.addons).*.name) }}
          include.*.version: ${{ toJSON(fromJSON(steps.addons.outputs.addons).*.version) }}

  build:
      name: Publish ${{ matrix.name }} ${{ matrix.version }}
      runs-on: ubuntu-latest
      needs: check-addon-changes
      if: ${{ needs.check-addon-changes.outputs.matrix != '{}' }}
      permissions:
        contents: write
      strategy:
        matrix: ${{ fromJson(needs.check-addon-changes.outputs.matrix) }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Publish ${{ matrix.name }} ${{ matrix.version }} to Docker Hub
          uses: ./.github/actions/docker
          with:
            ADDON_NAME: ${{ matrix.package.name }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCKERHUB_PUBLISH: false
