name: CI on pull request (build addon)

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-addon-changes:
    name: Check addon changes
    runs-on: ubuntu-latest
    outputs:
      changedAddons: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 📂 Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            addons: 
              - 'addons/**'
      # - name: Prepare repository
      #   uses: ./.github/actions/prepare
      #   with:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Test build
      #   uses: home-assistant/builder@master
      #   with:
      #     args: |
      #       --test \
      #       --all \
      #       --target ${{ matrix.addon }} \
      #       --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
