name: Release addons

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release addons
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-packages-matrix.outputs.json }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release Pull Request and Publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: Release addons
          commit: Version addons
          version: pnpm changeset:version
          publish: pnpm changeset:tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display published packages
        run: echo "${{ steps.changesets.outputs.publishedPackages }}"
      - name: Set packages output
        id: set-packages-matrix
        uses: nickofthyme/object-remap@v3
        with:
          include.*.name: ${{ toJSON(fromJSON(steps.changesets.outputs.publishedPackages).*.name) }}
          include.*.version: ${{ toJSON(fromJSON(steps.changesets.outputs.publishedPackages).*.version) }}
      - name: Print
        run: |
          echo ${{ steps.set-packages-matrix.outputs.json }}
  publish:
    name: Publish ${{ matrix.name }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.matrix != '{}' }}
    strategy:
      matrix: ${{ fromJson(needs.release.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "${{ matrix.name }}"
      # - name: Publish to Docker Hub
      #   uses: ./.github/actions/docker
      #   with:
      #     ADDON_NAME: ${{ matrix.package.name }}
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DOCKERHUB_PUBLISH: true
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}