name: Release addons

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release addons
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages-matrix.outputs.packages }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release Pull Request and Publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: Release addons
          commit: Version addons
          version: pnpm changeset:version
          publish: pnpm changeset:tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display published packages
        run: echo "${{ steps.changesets.outputs.publishedPackages }}"
      - name: Set packages output
        id: set-packages-matrix
        run: |
          set -eux
          MATRIX=$(echo ${{ steps.changesets.outputs.publishedPackages }} | jq -c '. | map(split("/")[0]) | unique')
          echo "packages=$MATRIX" >> $GITHUB_OUTPUT
        # run: echo "packages=${{ toJson(steps.changesets.outputs.publishedPackages) }}" >> $GITHUB_OUTPUT
      - name: Print
        run: |
          echo ${{ steps.set-packages-matrix.outputs.packages }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.packages != '' && needs.release.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.packages) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - run: echo "${{ needs.release.outputs.packages }}"
      # - run: echo "${{ fromJson(toJson(needs.release.outputs.packages)) }}"
      # - run: echo "${{ fromJson(needs.release.outputs.packages) }}"
      
      - run: echo "${{ matrix.package.name }}"
      # - name: Publish to Docker Hub
      #   uses: ./.github/actions/docker
      #   with:
      #     ADDON_NAME: ${{ matrix.package.name }}
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DOCKERHUB_PUBLISH: true
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}